import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
async function main() {
  await prisma.tourStop.deleteMany();
  await prisma.tour.deleteMany();
  await prisma.attraction.deleteMany();
  const attractions = await Promise.all([
    prisma.attraction.create({ data: { name: 'Cape Point', slug: 'cape-point', region: 'Cape Peninsula', shortDescription: 'Dramatic cliffs, ocean views, and one of the iconic natural highlights of Cape Town.', fullDescription: 'Cape Point is a must-visit for travellers wanting big scenery, ocean panoramas, rugged coastlines, and a classic full-day Cape Peninsula experience.', estimatedVisitMinutes: 120, entranceFee: 400, tags: JSON.stringify(['scenic','nature','photography','iconic']), imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1400&q=80' } }),
    prisma.attraction.create({ data: { name: 'Boulders Beach', slug: 'boulders-beach', region: 'Simons Town', shortDescription: 'Meet the famous African penguins on a protected beach.', fullDescription: 'Boulders Beach is one of the best family-friendly and wildlife-focused stops on the peninsula route.', estimatedVisitMinutes: 90, entranceFee: 190, tags: JSON.stringify(['family','wildlife','beach','photography']), imageUrl: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?auto=format&fit=crop&w=1400&q=80' } }),
    prisma.attraction.create({ data: { name: 'Table Mountain', slug: 'table-mountain', region: 'City Bowl', shortDescription: 'Cape Town\'s most iconic landmark with incredible panoramic views.', fullDescription: 'Table Mountain is a signature Cape Town experience and pairs well with city exploration and a relaxed private day tour.', estimatedVisitMinutes: 120, entranceFee: 420, tags: JSON.stringify(['scenic','iconic','nature','photography']), imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1400&q=80' } }),
    prisma.attraction.create({ data: { name: 'Bo-Kaap', slug: 'bo-kaap', region: 'Cape Town CBD', shortDescription: 'A colourful cultural neighbourhood filled with history and local character.', fullDescription: 'Bo-Kaap is perfect for travellers who want culture, history, architecture, and local stories alongside their city tour.', estimatedVisitMinutes: 60, entranceFee: 0, tags: JSON.stringify(['culture','history','city','food','photography']), imageUrl: 'https://images.unsplash.com/photo-1580394693936-d0a56f2b0957?auto=format&fit=crop&w=1400&q=80' } }),
    prisma.attraction.create({ data: { name: 'Stellenbosch', slug: 'stellenbosch', region: 'Cape Winelands', shortDescription: 'Historic wine region known for estates, tasting rooms, and mountain scenery.', fullDescription: 'Stellenbosch is one of the most popular Cape Winelands stops and suits couples, groups, and premium travellers.', estimatedVisitMinutes: 180, entranceFee: 0, tags: JSON.stringify(['wine','food','luxury','scenic']), imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1400&q=80' } }),
    prisma.attraction.create({ data: { name: 'Franschhoek', slug: 'franschhoek', region: 'Cape Winelands', shortDescription: 'A premium wine and food destination ideal for leisurely tastings.', fullDescription: 'Franschhoek is a premium destination for wine lovers, culinary travellers, and guests seeking an elegant relaxed day out.', estimatedVisitMinutes: 180, entranceFee: 0, tags: JSON.stringify(['wine','food','luxury','romantic']), imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1400&q=80' } }),
    prisma.attraction.create({ data: { name: "Chapman's Peak Drive", slug: 'chapmans-peak-drive', region: 'Atlantic Seaboard', shortDescription: "One of the world's most scenic coastal drives.", fullDescription: "Chapman's Peak Drive is a high-impact scenic route with viewpoint stops, often included in Cape Point itineraries.", estimatedVisitMinutes: 45, entranceFee: 0, tags: JSON.stringify(['scenic','road-trip','photography','iconic']), imageUrl: 'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?auto=format&fit=crop&w=1400&q=80' } }),
    prisma.attraction.create({ data: { name: 'Kirstenbosch Botanical Garden', slug: 'kirstenbosch-botanical-garden', region: 'Newlands', shortDescription: 'A world-famous botanical garden at the foot of Table Mountain.', fullDescription: 'Kirstenbosch offers a more relaxed pace for travellers interested in nature, photography, and scenic gardens.', estimatedVisitMinutes: 120, entranceFee: 250, tags: JSON.stringify(['nature','family','relaxed','photography']), imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=1400&q=80' } })
  ]);
  const bySlug = Object.fromEntries(attractions.map((a) => [a.slug, a]));
  const t1 = await prisma.tour.create({ data: { title: 'Full Day Cape Point Tour', slug: 'full-day-cape-point-tour', summary: 'An iconic full-day peninsula journey covering dramatic coastlines, penguins, and scenic drives.', description: 'Experience the best of the Cape Peninsula with stops that showcase ocean views, wildlife, and unforgettable landscapes.', durationType: 'Full Day', priceFrom: 2200, category: 'Nature & Scenic', isPrivate: true, isFeatured: true, highlights: JSON.stringify(['Cape Point','Boulders Beach',"Chapman's Peak Drive"]), imageUrl: bySlug['cape-point'].imageUrl, stops: { create: [{ attractionId: bySlug['chapmans-peak-drive'].id, stopOrder: 1, suggestedStopMinutes: 45 }, { attractionId: bySlug['boulders-beach'].id, stopOrder: 2, suggestedStopMinutes: 90 }, { attractionId: bySlug['cape-point'].id, stopOrder: 3, suggestedStopMinutes: 120 }] } } });
  const t2 = await prisma.tour.create({ data: { title: 'Half Day Cape Town City Tour', slug: 'half-day-cape-town-city-tour', summary: 'A compact introduction to the city\'s culture, colour, and iconic views.', description: 'See the essential city highlights in a practical half-day format.', durationType: 'Half Day', priceFrom: 1400, category: 'City & Culture', isPrivate: true, isFeatured: true, highlights: JSON.stringify(['Bo-Kaap','Table Mountain','City orientation']), imageUrl: bySlug['table-mountain'].imageUrl, stops: { create: [{ attractionId: bySlug['bo-kaap'].id, stopOrder: 1, suggestedStopMinutes: 60 }, { attractionId: bySlug['table-mountain'].id, stopOrder: 2, suggestedStopMinutes: 120 }] } } });
  const t3 = await prisma.tour.create({ data: { title: 'Full Day Cape Winelands Tour', slug: 'full-day-cape-winelands-tour', summary: 'A full-day wine, food, and scenery experience through the Cape Winelands.', description: 'Perfect for couples and premium travellers who want wine tastings, beautiful estates, and a slower luxury rhythm.', durationType: 'Full Day', priceFrom: 2600, category: 'Wine & Food', isPrivate: true, isFeatured: true, highlights: JSON.stringify(['Stellenbosch','Franschhoek','Estate tastings']), imageUrl: bySlug['stellenbosch'].imageUrl, stops: { create: [{ attractionId: bySlug['stellenbosch'].id, stopOrder: 1, suggestedStopMinutes: 180 }, { attractionId: bySlug['franschhoek'].id, stopOrder: 2, suggestedStopMinutes: 180 }] } } });
  console.log('Seeded', attractions.length, 'attractions and 3 tours:', t1.title, '|', t2.title, '|', t3.title);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(async () => { await prisma.$disconnect(); });
