import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET(request: Request) {
  const url = new URL(request.url);
  if (url.searchParams.get('secret') !== process.env.ADMIN_PASSWORD) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  await prisma.tourStop.deleteMany();
  await prisma.tour.deleteMany();
  await prisma.attraction.deleteMany();
  const a = await Promise.all([
    prisma.attraction.create({data:{name:'Cape Point',slug:'cape-point',region:'Cape Peninsula',shortDescription:'Dramatic cliffs and ocean views.',fullDescription:'Cape Point is a must-visit for big scenery and ocean panoramas.',estimatedVisitMinutes:120,entranceFee:400,tags:['scenic','nature','iconic'],imageUrl:'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1400&q=80'}}),
    prisma.attraction.create({data:{name:'Boulders Beach',slug:'boulders-beach',region:'Simons Town',shortDescription:'Meet the famous African penguins.',fullDescription:'Family-friendly wildlife stop on the peninsula route.',estimatedVisitMinutes:90,entranceFee:190,tags:['family','wildlife','beach'],imageUrl:'https://images.unsplash.com/photo-1474511320723-9a56873867b5?auto=format&fit=crop&w=1400&q=80'}}),
    prisma.attraction.create({data:{name:'Table Mountain',slug:'table-mountain',region:'City Bowl',shortDescription:"Cape Town's most iconic landmark.",fullDescription:'Signature Cape Town experience with panoramic views.',estimatedVisitMinutes:120,entranceFee:420,tags:['scenic','iconic','nature'],imageUrl:'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=1400&q=80'}}),
    prisma.attraction.create({data:{name:'Bo-Kaap',slug:'bo-kaap',region:'Cape Town CBD',shortDescription:'Colourful cultural neighbourhood.',fullDescription:'Perfect for culture, history, and local stories.',estimatedVisitMinutes:60,entranceFee:0,tags:['culture','history','city'],imageUrl:'https://images.unsplash.com/photo-1580394693936-d0a56f2b0957?auto=format&fit=crop&w=1400&q=80'}}),
    prisma.attraction.create({data:{name:'Stellenbosch',slug:'stellenbosch',region:'Cape Winelands',shortDescription:'Historic wine region.',fullDescription:'Popular Winelands stop for wine and food lovers.',estimatedVisitMinutes:180,entranceFee:0,tags:['wine','food','luxury'],imageUrl:'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1400&q=80'}}),
    prisma.attraction.create({data:{name:'Franschhoek',slug:'franschhoek',region:'Cape Winelands',shortDescription:'Premium wine and food destination.',fullDescription:'Elegant destination for wine lovers.',estimatedVisitMinutes:180,entranceFee:0,tags:['wine','food','romantic'],imageUrl:'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1400&q=80'}}),
    prisma.attraction.create({data:{name:"Chapman's Peak Drive",slug:'chapmans-peak-drive',region:'Atlantic Seaboard',shortDescription:"One of the world's most scenic coastal drives.",fullDescription:'High-impact scenic route with viewpoint stops.',estimatedVisitMinutes:45,entranceFee:0,tags:['scenic','photography','iconic'],imageUrl:'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?auto=format&fit=crop&w=1400&q=80'}}),
    prisma.attraction.create({data:{name:'Kirstenbosch Botanical Garden',slug:'kirstenbosch-botanical-garden',region:'Newlands',shortDescription:'World-famous botanical garden.',fullDescription:'Relaxed nature and photography stop.',estimatedVisitMinutes:120,entranceFee:250,tags:['nature','family','relaxed'],imageUrl:'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=1400&q=80'}}),
  ]);
  const b = Object.fromEntries(a.map((x) => [x.slug, x]));
  const t1 = await prisma.tour.create({data:{title:'Full Day Cape Point Tour',slug:'full-day-cape-point-tour',summary:'An iconic full-day peninsula journey.',description:'Experience the best of the Cape Peninsula.',durationType:'Full Day',priceFrom:2200,category:'Nature & Scenic',isPrivate:true,isFeatured:true,highlights:['Cape Point','Boulders Beach',"Chapman's Peak"],imageUrl:b['cape-point'].imageUrl,stops:{create:[{attractionId:b['chapmans-peak-drive'].id,stopOrder:1},{attractionId:b['boulders-beach'].id,stopOrder:2},{attractionId:b['cape-point'].id,stopOrder:3}]}}});
  const t2 = await prisma.tour.create({data:{title:'Half Day Cape Town City Tour',slug:'half-day-cape-town-city-tour',summary:"A compact introduction to the city's culture.",description:'Essential city highlights in half a day.',durationType:'Half Day',priceFrom:1400,category:'City & Culture',isPrivate:true,isFeatured:true,highlights:['Bo-Kaap','Table Mountain'],imageUrl:b['table-mountain'].imageUrl,stops:{create:[{attractionId:b['bo-kaap'].id,stopOrder:1},{attractionId:b['table-mountain'].id,stopOrder:2}]}}});
  const t3 = await prisma.tour.create({data:{title:'Full Day Cape Winelands Tour',slug:'full-day-cape-winelands-tour',summary:'Wine, food, and scenery through the Winelands.',description:'Perfect for couples and premium travellers.',durationType:'Full Day',priceFrom:2600,category:'Wine & Food',isPrivate:true,isFeatured:true,highlights:['Stellenbosch','Franschhoek'],imageUrl:b['stellenbosch'].imageUrl,stops:{create:[{attractionId:b['stellenbosch'].id,stopOrder:1},{attractionId:b['franschhoek'].id,stopOrder:2}]}}});
  return NextResponse.json({success:true,attractions:a.length,tours:[t1.title,t2.title,t3.title]});
}
